export const CLIENT_ID = "586990699149-mf4qeqt0f33bine5135ai4t4feibkp2c.apps.googleusercontent.com"
export const CLIENT_SECRET = "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"
export const REDIRECT_URI = "http://localhost:4000/admin/auth/google/callback"
export const SCOPE = "https://www.googleapis.com/auth/userinfo.email "
export const REDIRECT_URI_END = "http://localhost:4000/admin/home"